server:
  port:

spring:
  boot:
    admin:
      url: https://micro-service-admin-service.herokuapp.com:80
management:
  security:
    enabled: false

datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
  initialize: true
  sql-script-encoding: UTF-8