server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://localhost:8000
        instance:
          management-base-url: ${spring.boot.admin.client.url}
          service-base-url: ${spring.boot.admin.client.url}
        auto-deregistration: true
        period: 5s
management.security.enabled: false

datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
  initialize: true
  sql-script-encoding: UTF-8