server:
  port: 8080
logging:
  level:
    org.woodwhale.king: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    initialize: true
    sql-script-encoding: UTF-8
  boot:
    admin:
      client:
        url: http://localhost:8000
        instance:
          management-base-url:
          service-base-url:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
        auto-deregistration: true
        period: 5s
  security.user:
    name: admin
    password: admin
management:
  security.enabled: true
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: ALWAYS
