server:
  port:
logging:
  level:
    org.woodwhale.king: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    initialize: true
    sql-script-encoding: UTF-8
  boot:
    admin:
      client:
        url: https://micro-service-admin-service.herokuapp.com
        instance:
          management-base-url: ${spring.boot.admin.client.url}
          service-base-url: ${spring.boot.admin.client.url}
        auto-deregistration: true
        period: 5s
        metadata:
          user.name: ${spring.security.user.name}
          user.password: ${spring.security.user.password}
  security:
    user:
      name: admin
      password: admin
  management.security.enabled: true
